# Generated by Django 4.2.3 on 2023-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
